// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHomePage():Promise<string>;

export function SaveUserPreferences(arg1:main.UserPreferences):Promise<void>;
